import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { pretendard } from '@/styles/fonts';
import { globalColors } from '@/styles/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.className} ${globalColors}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
